@baseUrl = https://smsethiopia.et/api
@apiKey = 2U2MFDKCQS0PH32EYMDNE2XU68AM3A4E:375

### Get Attendance with Variables
POST {{baseUrl}}/sms/send
KEY: {{apiKey}}
Content-Type: application/json

{
  "msisdn": "251975123630",
  "text": "Test message from Mohamed Eltoum, Banan-IT."
}
###
